name: genius_ai
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0
  dio: ^5.3.3
  fpdart: ^1.1.0
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  go_router: ^12.0.1
  internet_connection_checker_plus: ^2.1.0
  fluttertoast: ^8.2.2
  flutter_adaptive_scaffold: ^0.1.7+1
  crisp_chat: ^0.0.4
  envied: ^0.5.1
  dart_openai: ^4.0.0
  markdown_widget: ^2.3.1
  flutter_downloader: ^1.11.4
  path_provider: ^2.1.1
  android_path_provider: ^0.3.0
  permission_handler: ^11.0.1
  just_audio: ^0.9.35
  replicate:
        git:
          url: https://github.com/stilyng94/replicate

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.5
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.3
  envied_generator: ^0.5.1


flutter:


  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/images/
    - assets/audio/
